return {
  "m4xshen/smartcolumn.nvim",
  opts = {
    colorcolumn = "80",
    disabled_filetypes = {
      "alpha",
      "dashboard",
      "checkhealth",
      "fzf",
      "help",
      "lazy",
      "lazygit",
      "markdown",
      "mason",
      "minifiles",
      "oil",
      "snacks_dashboard",
      "starter",
      "TelescopePrompt",
      "text",
      "toggleterm",
      "yazi",
    },
    custom_colorcolumn = {},
    scope = "file",
  },
}
